<a href="https://colab.research.google.com/github/uday89750-gif/Machine_learning-/blob/main/encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ordinal encoding

In [ ]:
import pandas as pd
import numpy as np
import sklearn as sk

In [ ]:
df= pd.read_csv("customer.csv",usecols=["education","review","purchased"])
df.sample(5)

     review education purchased
30  Average        UG        No
43     Poor        PG        No
9      Good        UG       Yes
3      Good        PG        No
23     Good    School        No

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(df.drop("purchased",axis=1),df['purchased'],test_size=0.3)
x_train.head()

     review education
34  Average    School
38     Good    School
22     Poor        PG
33     Good        PG
21  Average        PG

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['School','UG','PG'],['Poor','Average','Good']])

oe.fit(x_train[['education','review']])

x_train[['education','review']] = oe.transform(x_train[['education','review']])
x_test[['education','review']] = oe.transform(x_test[['education','review']])

In [ ]:
x_train = pd.DataFrame(x_train,columns=['review','education'])
x_test= pd.DataFrame(x_test,columns=['review','education'])

In [ ]:
x_train

    review  education
34     1.0        0.0
38     2.0        0.0
22     0.0        2.0
33     2.0        2.0
21     1.0        2.0
13     1.0        0.0
35     0.0        0.0
5      1.0        0.0
8      1.0        1.0
15     0.0        1.0
49     2.0        1.0
42     2.0        2.0
29     1.0        1.0
3      2.0        2.0
16     0.0        1.0
23     2.0        0.0
19     0.0        2.0
14     0.0        2.0
1      0.0        1.0
9      2.0        1.0
10     2.0        1.0
25     2.0        0.0
32     1.0        1.0
41     2.0        2.0
12     0.0        0.0
18     2.0        0.0
4      1.0        1.0
46     0.0        2.0
44     1.0        1.0
43     0.0        2.0
27     0.0        2.0
24     1.0        2.0
45     0.0        2.0
37     1.0        2.0
17     0.0        1.0

In [ ]:
df = pd.read_csv("cars.csv")
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [ ]:
df['brand'].nunique()

32

In [ ]:
#encoding using pandas
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [ ]:
#encoding using sklearn
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype = np.int32)
x_train_encoded = ohe.fit_transform(x_train[['fuel','owner']])
x_test_encoded = ohe.transform(x_test[['fuel','owner']])

In [ ]:
x_train_combined=np.hstack((x_train[['brand','km_driven']].values,x_train_encoded))

In [ ]:
x_train_combined

array([['Hyundai', 80000, 0, ..., 0, 0, 0],
       ['Chevrolet', 155000, 1, ..., 0, 0, 0],
       ['Toyota', 110000, 1, ..., 0, 0, 0],
       ...,
       ['Jeep', 87500, 1, ..., 0, 0, 0],
       ['Chevrolet', 90000, 1, ..., 1, 0, 0],
       ['Maruti', 117000, 1, ..., 0, 0, 0]], dtype=object)

In [ ]:
# x_train_combined=pd.DataFrame(x_train_combined,columns=x_train_combined.get_feature_names_out())
# x_test_encoded=pd.DataFrame(x_test_encoded,columns=x_train_combined.get_feature_names_out())

In [ ]:
#column transformer
df= pd.read_csv("covid_toy.csv")
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=["has_covid"]),df["has_covid"],test_size=0.2)

In [ ]:
y_test

5     Yes
42    Yes
75    Yes
70     No
31     No
50    Yes
80    Yes
85    Yes
57     No
49     No
88     No
21    Yes
89     No
96    Yes
45     No
36     No
84     No
29    Yes
2      No
62    Yes
Name: has_covid, dtype: object

In [ ]:
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers =[( 'tnf1',SimpleImputer(),['fever']),
( 'tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
('tnf3',OneHotEncoder(sparse_output = False,drop='first'),['gender','city'])],remainder = 'passthrough')

In [ ]:
x_train = transformer.fit_transform(x_train)
x_test = transformer.transform(x_test)

In [ ]:
x_train = pd.DataFrame(x_train,columns = transformer.get_feature_names_out())
x_test = pd.DataFrame(x_test,columns = transformer.get_feature_names_out())

In [ ]:
x_train.shape

(80, 7)